apiVersion: v1
kind: Service
metadata:
  name: color-palette-api
  namespace: color-palette-api
spec:
  selector:
    app: color-palette-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
