apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: color-palette-api
resources:
  - ../../base
images:
  - name: sample-app
    newName: 498507275411.dkr.ecr.us-east-1.amazonaws.com/sample-app
    newTag: 5f66c20b07f8ebbc705896fcff08609d46dc8faf #00fc79e46d05195f5d1adcf69b79365720ae7e8c  # Replace <COMMIT_SHA> with latest GitHub SHA that was pushed to ECR.
