apiVersion: v1
kind: Service
metadata:
  name: color-palette-api-alb
  namespace: color-palette-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  selector:
    app: color-palette-api
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
