name: CI - Build, Test & Push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  #for manual trigger

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sample-app #color-palette-api

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------
      # Checkout source code
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Node.js setup & tests
      # ----------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/service/package-lock.json

      - name: Install dependencies
        working-directory: app/service
        run: npm ci

      - name: Run tests
        working-directory: app/service
        run: npm test

      # ----------------------------
      # Static Application Security Testing (SAST)
      # ----------------------------
      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci

      - name: Security audit
        working-directory: app/service
        run: npm audit --audit-level=high

      # ----------------------------
      # AWS authentication (OIDC)
      # ----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      # ----------------------------
      # Login to Amazon ECR
      # ----------------------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      # ----------------------------
      # Build Docker image
      # ----------------------------
      - name: Build Docker image
        working-directory: app/service
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPOSITORY}
          echo "Building image: $ECR_URI:$IMAGE_TAG"
          docker build -t $ECR_URI:$IMAGE_TAG .

      # ----------------------------
      # Container Image Security Scan
      # ----------------------------
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: 'table'
          exit-code: 0 #'1'
          vuln-type: os,library
          severity:  'HIGH' #'CRITICAL,HIGH' # TODO: Re-enable Trivy with stricter gating after dependency cleanup

      # ----------------------------
      # Push Docker image to ECR
      # ----------------------------
      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPOSITORY}
          docker push $ECR_URI:$IMAGE_TAG

      # ----------------------------
      # Update Kustomize newTag automatically
      # ----------------------------
      - name: Update kustomization.yaml with new SHA
        run: |
          IMAGE_TAG=${{ github.sha }}
          KUSTOMIZE_FILE=k8s/overlays/dev/kustomization.yaml

          # Install Go yq
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

          # Update newTag using yq
          yq eval ".images[0].newTag = \"$IMAGE_TAG\"" -i $KUSTOMIZE_FILE

      - name: Update kustomization.yaml and create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "ci: update kustomization newTag to ${{ github.sha }} [skip ci]"
          branch: "update-kustomization-${{ github.sha }}"
          title: "Update kustomization.yaml newTag"
          body: "Automatic update of image tag to ${{ github.sha }}"
          base: main

